/* Erzeugt von pflege/baue-werte.js - NICHT von Hand aendern. */
/* Stand 2026-09-10. Zum Aktualisieren die Zahlen im Pflegeskript ersetzen. */
const WERTE = {
 "stand": "2026-09-10",
 "eurUsd": 1.1652,
 "hinweis": "Startkurse und Kennzahlen sind echte Marktdaten vom angegebenen Stand. Der Kursverlauf im Spiel ist simuliert und hat keinen Bezug zur Wirklichkeit.",
 "quellen": [
  "stockanalysis.com (Kurse, KGV, Dividendenrendite, ETF-Kennzahlen)",
  "CoinGecko (Kryptokurse)",
  "frankfurter.dev / EZB (Wechselkurse)"
 ],
 "werte": [
  {
   "id": "sap",
   "art": "aktie",
   "name": "SAP",
   "kuerzel": "SAP",
   "kurs": 178.34,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 27.38,
   "gewinnJeAktie": 6.5135,
   "dividende": 2.4611,
   "divRendite": 1.38,
   "sektor": "Technologie",
   "land": "Deutschland"
  },
  {
   "id": "sie",
   "art": "aktie",
   "name": "Siemens",
   "kuerzel": "SIE",
   "kurs": 263.45,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 26.43,
   "gewinnJeAktie": 9.9678,
   "dividende": 5.2427,
   "divRendite": 1.99,
   "sektor": "Industrie",
   "land": "Deutschland"
  },
  {
   "id": "alv",
   "art": "aktie",
   "name": "Allianz",
   "kuerzel": "ALV",
   "kurs": 439.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.33,
   "gewinnJeAktie": 30.6699,
   "dividende": 16.745,
   "divRendite": 3.81,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "rhm",
   "art": "aktie",
   "name": "Rheinmetall",
   "kuerzel": "RHM",
   "kurs": 1015,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 38.8,
   "gewinnJeAktie": 26.1598,
   "dividende": 10.759,
   "divRendite": 1.06,
   "sektor": "Ruestung",
   "land": "Deutschland"
  },
  {
   "id": "mbg",
   "art": "aktie",
   "name": "Mercedes-Benz Group",
   "kuerzel": "MBG",
   "kurs": 47.07,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 8.84,
   "gewinnJeAktie": 5.3247,
   "dividende": 3.4644,
   "divRendite": 7.36,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "bmw",
   "art": "aktie",
   "name": "BMW",
   "kuerzel": "BMW",
   "kurs": 62.94,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 5.95,
   "gewinnJeAktie": 10.5782,
   "dividende": 4.3492,
   "divRendite": 6.91,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "vow3",
   "art": "aktie",
   "name": "Volkswagen Vorzuege",
   "kuerzel": "VOW3",
   "kurs": 81.92,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 7.81,
   "gewinnJeAktie": 10.4891,
   "dividende": 5.8491,
   "divRendite": 7.14,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "dbk",
   "art": "aktie",
   "name": "Deutsche Bank",
   "kuerzel": "DBK",
   "kurs": 35.18,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.31,
   "gewinnJeAktie": 3.1105,
   "dividende": 1.0097,
   "divRendite": 2.87,
   "sektor": "Banken",
   "land": "Deutschland"
  },
  {
   "id": "cbk",
   "art": "aktie",
   "name": "Commerzbank",
   "kuerzel": "CBK",
   "kurs": 42.43,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.17,
   "gewinnJeAktie": 2.624,
   "dividende": 1.1371,
   "divRendite": 2.68,
   "sektor": "Banken",
   "land": "Deutschland"
  },
  {
   "id": "ads",
   "art": "aktie",
   "name": "adidas",
   "kuerzel": "ADS",
   "kurs": 142.95,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 18.81,
   "gewinnJeAktie": 7.5997,
   "dividende": 2.6732,
   "divRendite": 1.87,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "zal",
   "art": "aktie",
   "name": "Zalando",
   "kuerzel": "ZAL",
   "kurs": 22.67,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 62.21,
   "gewinnJeAktie": 0.364411,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Handel",
   "land": "Deutschland"
  },
  {
   "id": "ifx",
   "art": "aktie",
   "name": "Infineon",
   "kuerzel": "IFX",
   "kurs": 56.82,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 61.88,
   "gewinnJeAktie": 0.918229,
   "dividende": 0.352284,
   "divRendite": 0.62,
   "sektor": "Halbleiter",
   "land": "Deutschland"
  },
  {
   "id": "bas",
   "art": "aktie",
   "name": "BASF",
   "kuerzel": "BAS",
   "kurs": 52.56,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 22.27,
   "gewinnJeAktie": 2.3601,
   "dividende": 2.218,
   "divRendite": 4.22,
   "sektor": "Chemie",
   "land": "Deutschland"
  },
  {
   "id": "bayn",
   "art": "aktie",
   "name": "Bayer",
   "kuerzel": "BAYN",
   "kurs": 49.08,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.107976,
   "divRendite": 0.22,
   "sektor": "Pharma",
   "land": "Deutschland"
  },
  {
   "id": "mrk1",
   "art": "aktie",
   "name": "Merck",
   "kuerzel": "MRK1",
   "kurs": 132.1,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 24.35,
   "gewinnJeAktie": 5.4251,
   "dividende": 2.1004,
   "divRendite": 1.59,
   "sektor": "Pharma",
   "land": "Deutschland"
  },
  {
   "id": "dte",
   "art": "aktie",
   "name": "Deutsche Telekom",
   "kuerzel": "DTE",
   "kurs": 27.78,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 15.55,
   "gewinnJeAktie": 1.7865,
   "dividende": 0.966744,
   "divRendite": 3.48,
   "sektor": "Telekom",
   "land": "Deutschland"
  },
  {
   "id": "dhl",
   "art": "aktie",
   "name": "DHL Group",
   "kuerzel": "DHL",
   "kurs": 54.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.58,
   "gewinnJeAktie": 3.3052,
   "dividende": 1.8961,
   "divRendite": 3.46,
   "sektor": "Logistik",
   "land": "Deutschland"
  },
  {
   "id": "eoan",
   "art": "aktie",
   "name": "E.ON",
   "kuerzel": "EOAN",
   "kurs": 17.69,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.64,
   "gewinnJeAktie": 1.2969,
   "dividende": 0.578463,
   "divRendite": 3.27,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "rwe",
   "art": "aktie",
   "name": "RWE",
   "kuerzel": "RWE",
   "kurs": 60.44,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.34,
   "gewinnJeAktie": 4.5307,
   "dividende": 1.2511,
   "divRendite": 2.07,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "enr",
   "art": "aktie",
   "name": "Siemens Energy",
   "kuerzel": "ENR",
   "kurs": 144.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 47.21,
   "gewinnJeAktie": 3.0671,
   "dividende": 0.69504,
   "divRendite": 0.48,
   "sektor": "Versorger",
   "land": "Deutschland"
  },
  {
   "id": "muv2",
   "art": "aktie",
   "name": "Muenchener Rueck",
   "kuerzel": "MUV2",
   "kurs": 502.2,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 9.23,
   "gewinnJeAktie": 54.4095,
   "dividende": 23.051,
   "divRendite": 4.59,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "hnr1",
   "art": "aktie",
   "name": "Hannover Rueck",
   "kuerzel": "HNR1",
   "kurs": 248.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 10.85,
   "gewinnJeAktie": 22.9124,
   "dividende": 11.9079,
   "divRendite": 4.79,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "db1",
   "art": "aktie",
   "name": "Deutsche Boerse",
   "kuerzel": "DB1",
   "kurs": 275.7,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 23.6,
   "gewinnJeAktie": 11.6822,
   "dividende": 4.0804,
   "divRendite": 1.48,
   "sektor": "Finanzen",
   "land": "Deutschland"
  },
  {
   "id": "bei",
   "art": "aktie",
   "name": "Beiersdorf",
   "kuerzel": "BEI",
   "kurs": 73.84,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 17.42,
   "gewinnJeAktie": 4.2388,
   "dividende": 0.967304,
   "divRendite": 1.31,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "hen3",
   "art": "aktie",
   "name": "Henkel Vorzuege",
   "kuerzel": "HEN3",
   "kurs": 73.7,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 15.82,
   "gewinnJeAktie": 4.6587,
   "dividende": 2.0194,
   "divRendite": 2.74,
   "sektor": "Konsum",
   "land": "Deutschland"
  },
  {
   "id": "con",
   "art": "aktie",
   "name": "Continental",
   "kuerzel": "CON",
   "kurs": 70.12,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 2.7417,
   "divRendite": 3.91,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "dtg",
   "art": "aktie",
   "name": "Daimler Truck",
   "kuerzel": "DTG",
   "kurs": 43.76,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 31.15,
   "gewinnJeAktie": 1.4048,
   "dividende": 1.8423,
   "divRendite": 4.21,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "mtx",
   "art": "aktie",
   "name": "MTU Aero Engines",
   "kuerzel": "MTX",
   "kurs": 344.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 19.91,
   "gewinnJeAktie": 17.3179,
   "dividende": 3.6204,
   "divRendite": 1.05,
   "sektor": "Luftfahrt",
   "land": "Deutschland"
  },
  {
   "id": "hei",
   "art": "aktie",
   "name": "Heidelberg Materials",
   "kuerzel": "HEI",
   "kurs": 156.35,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.66,
   "gewinnJeAktie": 11.4458,
   "dividende": 3.4397,
   "divRendite": 2.2,
   "sektor": "Bau",
   "land": "Deutschland"
  },
  {
   "id": "vna",
   "art": "aktie",
   "name": "Vonovia",
   "kuerzel": "VNA",
   "kurs": 18.44,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 4.34,
   "gewinnJeAktie": 4.2488,
   "dividende": 1.2004,
   "divRendite": 6.51,
   "sektor": "Immobilien",
   "land": "Deutschland"
  },
  {
   "id": "asml",
   "art": "aktie",
   "name": "ASML",
   "kuerzel": "ASML",
   "kurs": 1475.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 54.38,
   "gewinnJeAktie": 27.1313,
   "dividende": 7.6721,
   "divRendite": 0.52,
   "sektor": "Halbleiter",
   "land": "Niederlande"
  },
  {
   "id": "mc",
   "art": "aktie",
   "name": "LVMH",
   "kuerzel": "MC",
   "kurs": 408.95,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 18.75,
   "gewinnJeAktie": 21.8107,
   "dividende": 12.3503,
   "divRendite": 3.02,
   "sektor": "Luxus",
   "land": "Frankreich"
  },
  {
   "id": "rms",
   "art": "aktie",
   "name": "Hermes",
   "kuerzel": "RMS",
   "kurs": 1421,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 32.77,
   "gewinnJeAktie": 43.3628,
   "dividende": 17.1941,
   "divRendite": 1.21,
   "sektor": "Luxus",
   "land": "Frankreich"
  },
  {
   "id": "or",
   "art": "aktie",
   "name": "LOreal",
   "kuerzel": "OR",
   "kurs": 377.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 32.4,
   "gewinnJeAktie": 11.6605,
   "dividende": 7.0649,
   "divRendite": 1.87,
   "sektor": "Konsum",
   "land": "Frankreich"
  },
  {
   "id": "tte",
   "art": "aktie",
   "name": "TotalEnergies",
   "kuerzel": "TTE",
   "kurs": 78.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.13,
   "gewinnJeAktie": 7.062,
   "dividende": 3.5999,
   "divRendite": 4.58,
   "sektor": "Energie",
   "land": "Frankreich"
  },
  {
   "id": "san",
   "art": "aktie",
   "name": "Sanofi",
   "kuerzel": "SAN",
   "kurs": 74.03,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 22.86,
   "gewinnJeAktie": 3.2384,
   "dividende": 3.9976,
   "divRendite": 5.4,
   "sektor": "Pharma",
   "land": "Frankreich"
  },
  {
   "id": "ai",
   "art": "aktie",
   "name": "Air Liquide",
   "kuerzel": "AI",
   "kurs": 168.58,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 30.29,
   "gewinnJeAktie": 5.5655,
   "dividende": 3.2705,
   "divRendite": 1.94,
   "sektor": "Chemie",
   "land": "Frankreich"
  },
  {
   "id": "su",
   "art": "aktie",
   "name": "Schneider Electric",
   "kuerzel": "SU",
   "kurs": 291.3,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 34.85,
   "gewinnJeAktie": 8.3587,
   "dividende": 4.253,
   "divRendite": 1.46,
   "sektor": "Industrie",
   "land": "Frankreich"
  },
  {
   "id": "saf",
   "art": "aktie",
   "name": "SAFRAN",
   "kuerzel": "SAF",
   "kurs": 322.9,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 34.67,
   "gewinnJeAktie": 9.3135,
   "dividende": 3.2613,
   "divRendite": 1.01,
   "sektor": "Luftfahrt",
   "land": "Frankreich"
  },
  {
   "id": "cs",
   "art": "aktie",
   "name": "AXA",
   "kuerzel": "CS",
   "kurs": 43.21,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.59,
   "gewinnJeAktie": 3.7282,
   "dividende": 2.2728,
   "divRendite": 5.26,
   "sektor": "Versicherung",
   "land": "Frankreich"
  },
  {
   "id": "bnp",
   "art": "aktie",
   "name": "BNP Paribas",
   "kuerzel": "BNP",
   "kurs": 103.24,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 8.9,
   "gewinnJeAktie": 11.6,
   "dividende": 5.162,
   "divRendite": 5,
   "sektor": "Banken",
   "land": "Frankreich"
  },
  {
   "id": "dg",
   "art": "aktie",
   "name": "VINCI",
   "kuerzel": "DG",
   "kurs": 111.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.4,
   "gewinnJeAktie": 8.9839,
   "dividende": 4.9684,
   "divRendite": 4.46,
   "sektor": "Bau",
   "land": "Frankreich"
  },
  {
   "id": "bn",
   "art": "aktie",
   "name": "Danone",
   "kuerzel": "BN",
   "kurs": 62.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 20.85,
   "gewinnJeAktie": 2.9976,
   "dividende": 2.2063,
   "divRendite": 3.53,
   "sektor": "Nahrung",
   "land": "Frankreich"
  },
  {
   "id": "el",
   "art": "aktie",
   "name": "EssilorLuxottica",
   "kuerzel": "EL",
   "kurs": 147.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 27.84,
   "gewinnJeAktie": 5.3017,
   "dividende": 3.7195,
   "divRendite": 2.52,
   "sektor": "Konsum",
   "land": "Frankreich"
  },
  {
   "id": "air",
   "art": "aktie",
   "name": "Airbus",
   "kuerzel": "AIR",
   "kurs": 197.14,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 26.15,
   "gewinnJeAktie": 7.5388,
   "dividende": 3.2528,
   "divRendite": 1.65,
   "sektor": "Luftfahrt",
   "land": "Niederlande"
  },
  {
   "id": "race",
   "art": "aktie",
   "name": "Ferrari",
   "kuerzel": "RACE",
   "kurs": 352.55,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 37.5,
   "gewinnJeAktie": 9.4013,
   "dividende": 3.5608,
   "divRendite": 1.01,
   "sektor": "Automobil",
   "land": "Italien"
  },
  {
   "id": "adyen",
   "art": "aktie",
   "name": "Adyen",
   "kuerzel": "ADYEN",
   "kurs": 934.1,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 26.75,
   "gewinnJeAktie": 34.9196,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "Niederlande"
  },
  {
   "id": "inga",
   "art": "aktie",
   "name": "ING Group",
   "kuerzel": "INGA",
   "kurs": 31.66,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 10.6,
   "gewinnJeAktie": 2.9868,
   "dividende": 1.3044,
   "divRendite": 4.12,
   "sektor": "Banken",
   "land": "Niederlande"
  },
  {
   "id": "abi",
   "art": "aktie",
   "name": "AB InBev",
   "kuerzel": "ABI",
   "kurs": 67.6,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 16.59,
   "gewinnJeAktie": 4.0747,
   "dividende": 1.1357,
   "divRendite": 1.68,
   "sektor": "Nahrung",
   "land": "Belgien"
  },
  {
   "id": "itx",
   "art": "aktie",
   "name": "Inditex",
   "kuerzel": "ITX",
   "kurs": 54.92,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 26.5,
   "gewinnJeAktie": 2.0725,
   "dividende": 1.6915,
   "divRendite": 3.08,
   "sektor": "Handel",
   "land": "Spanien"
  },
  {
   "id": "san2",
   "art": "aktie",
   "name": "Banco Santander",
   "kuerzel": "SAN2",
   "kurs": 12.65,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.39,
   "gewinnJeAktie": 0.879083,
   "dividende": 0.24794,
   "divRendite": 1.96,
   "sektor": "Banken",
   "land": "Spanien"
  },
  {
   "id": "ibe",
   "art": "aktie",
   "name": "Iberdrola",
   "kuerzel": "IBE",
   "kurs": 20.07,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 24.42,
   "gewinnJeAktie": 0.821867,
   "dividende": 0.690408,
   "divRendite": 3.44,
   "sektor": "Versorger",
   "land": "Spanien"
  },
  {
   "id": "enel",
   "art": "aktie",
   "name": "Enel",
   "kuerzel": "ENEL",
   "kurs": 8.963,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 21.32,
   "gewinnJeAktie": 0.420403,
   "dividende": 0.488483,
   "divRendite": 5.45,
   "sektor": "Versorger",
   "land": "Italien"
  },
  {
   "id": "eni",
   "art": "aktie",
   "name": "Eni",
   "kuerzel": "ENI",
   "kurs": 23.92,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 12.57,
   "gewinnJeAktie": 1.9029,
   "dividende": 1.0812,
   "divRendite": 4.52,
   "sektor": "Energie",
   "land": "Italien"
  },
  {
   "id": "ucg",
   "art": "aktie",
   "name": "UniCredit",
   "kuerzel": "UCG",
   "kurs": 84.22,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.96,
   "gewinnJeAktie": 7.0418,
   "dividende": 3.1667,
   "divRendite": 3.76,
   "sektor": "Banken",
   "land": "Italien"
  },
  {
   "id": "isp",
   "art": "aktie",
   "name": "Intesa Sanpaolo",
   "kuerzel": "ISP",
   "kurs": 6.668,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.99,
   "gewinnJeAktie": 0.55613,
   "dividende": 0.376075,
   "divRendite": 5.64,
   "sektor": "Banken",
   "land": "Italien"
  },
  {
   "id": "nvda",
   "art": "aktie",
   "name": "NVIDIA",
   "kuerzel": "NVDA",
   "kurs": 191.96,
   "kursOriginal": 223.67,
   "waehrungOriginal": "USD",
   "kgv": 28.28,
   "gewinnJeAktie": 6.7878,
   "dividende": 0.86382,
   "divRendite": 0.45,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "aapl",
   "art": "aktie",
   "name": "Apple",
   "kuerzel": "AAPL",
   "kurs": 270.63,
   "kursOriginal": 315.34,
   "waehrungOriginal": "USD",
   "kgv": 36.17,
   "gewinnJeAktie": 7.4822,
   "dividende": 0.920142,
   "divRendite": 0.34,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "googl",
   "art": "aktie",
   "name": "Alphabet",
   "kuerzel": "GOOGL",
   "kurs": 283.77,
   "kursOriginal": 330.65,
   "waehrungOriginal": "USD",
   "kgv": 16.59,
   "gewinnJeAktie": 17.1049,
   "dividende": 0.766179,
   "divRendite": 0.27,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "msft",
   "art": "aktie",
   "name": "Microsoft",
   "kuerzel": "MSFT",
   "kurs": 421.94,
   "kursOriginal": 491.65,
   "waehrungOriginal": "USD",
   "kgv": 27.39,
   "gewinnJeAktie": 15.4049,
   "dividende": 3.1224,
   "divRendite": 0.74,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "amzn",
   "art": "aktie",
   "name": "Amazon",
   "kuerzel": "AMZN",
   "kurs": 216.62,
   "kursOriginal": 252.4,
   "waehrungOriginal": "USD",
   "kgv": 20.3,
   "gewinnJeAktie": 10.6709,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "avgo",
   "art": "aktie",
   "name": "Broadcom",
   "kuerzel": "AVGO",
   "kurs": 312.72,
   "kursOriginal": 364.38,
   "waehrungOriginal": "USD",
   "kgv": 46.51,
   "gewinnJeAktie": 6.7237,
   "dividende": 2.2203,
   "divRendite": 0.71,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "meta",
   "art": "aktie",
   "name": "Meta Platforms",
   "kuerzel": "META",
   "kurs": 561.01,
   "kursOriginal": 653.69,
   "waehrungOriginal": "USD",
   "kgv": 24.63,
   "gewinnJeAktie": 22.7775,
   "dividende": 1.7952,
   "divRendite": 0.32,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "tsla",
   "art": "aktie",
   "name": "Tesla",
   "kuerzel": "TSLA",
   "kurs": 315.66,
   "kursOriginal": 367.81,
   "waehrungOriginal": "USD",
   "kgv": 381.68,
   "gewinnJeAktie": 0.827028,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Automobil",
   "land": "USA"
  },
  {
   "id": "brkb",
   "art": "aktie",
   "name": "Berkshire Hathaway",
   "kuerzel": "BRK.B",
   "kurs": 434.88,
   "kursOriginal": 506.72,
   "waehrungOriginal": "USD",
   "kgv": 12.64,
   "gewinnJeAktie": 34.4051,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "mu",
   "art": "aktie",
   "name": "Micron Technology",
   "kuerzel": "MU",
   "kurs": 882.05,
   "kursOriginal": 1027.77,
   "waehrungOriginal": "USD",
   "kgv": 23.19,
   "gewinnJeAktie": 38.0358,
   "dividende": 0.52923,
   "divRendite": 0.06,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "jpm",
   "art": "aktie",
   "name": "JPMorgan Chase",
   "kuerzel": "JPM",
   "kurs": 304.42,
   "kursOriginal": 354.71,
   "waehrungOriginal": "USD",
   "kgv": 15.22,
   "gewinnJeAktie": 20.0013,
   "dividende": 5.1447,
   "divRendite": 1.69,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "wmt",
   "art": "aktie",
   "name": "Walmart",
   "kuerzel": "WMT",
   "kurs": 90.8256,
   "kursOriginal": 105.83,
   "waehrungOriginal": "USD",
   "kgv": 38.35,
   "gewinnJeAktie": 2.3683,
   "dividende": 0.853761,
   "divRendite": 0.94,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "amd",
   "art": "aktie",
   "name": "AMD",
   "kuerzel": "AMD",
   "kurs": 447.22,
   "kursOriginal": 521.095,
   "waehrungOriginal": "USD",
   "kgv": 133,
   "gewinnJeAktie": 3.3626,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "v",
   "art": "aktie",
   "name": "Visa",
   "kuerzel": "V",
   "kurs": 315.3,
   "kursOriginal": 367.39,
   "waehrungOriginal": "USD",
   "kgv": 31.28,
   "gewinnJeAktie": 10.0799,
   "dividende": 2.3017,
   "divRendite": 0.73,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "jnj",
   "art": "aktie",
   "name": "Johnson & Johnson",
   "kuerzel": "JNJ",
   "kurs": 229.21,
   "kursOriginal": 267.08,
   "waehrungOriginal": "USD",
   "kgv": 30.96,
   "gewinnJeAktie": 7.4034,
   "dividende": 4.6071,
   "divRendite": 2.01,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "csco",
   "art": "aktie",
   "name": "Cisco",
   "kuerzel": "CSCO",
   "kurs": 93.9152,
   "kursOriginal": 109.43,
   "waehrungOriginal": "USD",
   "kgv": 32.86,
   "gewinnJeAktie": 2.858,
   "dividende": 1.4463,
   "divRendite": 1.54,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "cost",
   "art": "aktie",
   "name": "Costco",
   "kuerzel": "COST",
   "kurs": 774.63,
   "kursOriginal": 902.6,
   "waehrungOriginal": "USD",
   "kgv": 45.4,
   "gewinnJeAktie": 17.0623,
   "dividende": 5.0351,
   "divRendite": 0.65,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "amat",
   "art": "aktie",
   "name": "Applied Materials",
   "kuerzel": "AMAT",
   "kurs": 402.38,
   "kursOriginal": 468.85,
   "waehrungOriginal": "USD",
   "kgv": 40.44,
   "gewinnJeAktie": 9.95,
   "dividende": 1.8107,
   "divRendite": 0.45,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "cat",
   "art": "aktie",
   "name": "Caterpillar",
   "kuerzel": "CAT",
   "kurs": 699.93,
   "kursOriginal": 815.56,
   "waehrungOriginal": "USD",
   "kgv": 35.15,
   "gewinnJeAktie": 19.9127,
   "dividende": 5.5994,
   "divRendite": 0.8,
   "sektor": "Industrie",
   "land": "USA"
  },
  {
   "id": "lrcx",
   "art": "aktie",
   "name": "Lam Research",
   "kuerzel": "LRCX",
   "kurs": 271.06,
   "kursOriginal": 315.84,
   "waehrungOriginal": "USD",
   "kgv": 54.83,
   "gewinnJeAktie": 4.9436,
   "dividende": 0.894498,
   "divRendite": 0.33,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "pltr",
   "art": "aktie",
   "name": "Palantir",
   "kuerzel": "PLTR",
   "kurs": 145.49,
   "kursOriginal": 169.53,
   "waehrungOriginal": "USD",
   "kgv": 144.99,
   "gewinnJeAktie": 1.0034,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "ko",
   "art": "aktie",
   "name": "Coca-Cola",
   "kuerzel": "KO",
   "kurs": 75.1373,
   "kursOriginal": 87.55,
   "waehrungOriginal": "USD",
   "kgv": 26.31,
   "gewinnJeAktie": 2.8558,
   "dividende": 1.8183,
   "divRendite": 2.42,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "cvx",
   "art": "aktie",
   "name": "Chevron",
   "kuerzel": "CVX",
   "kurs": 183.5,
   "kursOriginal": 213.81,
   "waehrungOriginal": "USD",
   "kgv": 20.53,
   "gewinnJeAktie": 8.9381,
   "dividende": 6.1106,
   "divRendite": 3.33,
   "sektor": "Energie",
   "land": "USA"
  },
  {
   "id": "unh",
   "art": "aktie",
   "name": "UnitedHealth",
   "kuerzel": "UNH",
   "kurs": 337.33,
   "kursOriginal": 393.06,
   "waehrungOriginal": "USD",
   "kgv": 25.3,
   "gewinnJeAktie": 13.3332,
   "dividende": 7.961,
   "divRendite": 2.36,
   "sektor": "Gesundheit",
   "land": "USA"
  },
  {
   "id": "hd",
   "art": "aktie",
   "name": "Home Depot",
   "kuerzel": "HD",
   "kurs": 266.43,
   "kursOriginal": 310.45,
   "waehrungOriginal": "USD",
   "kgv": 21.72,
   "gewinnJeAktie": 12.2666,
   "dividende": 7.9929,
   "divRendite": 3,
   "sektor": "Handel",
   "land": "USA"
  },
  {
   "id": "pg",
   "art": "aktie",
   "name": "Procter & Gamble",
   "kuerzel": "PG",
   "kurs": 122.42,
   "kursOriginal": 142.64,
   "waehrungOriginal": "USD",
   "kgv": 21.53,
   "gewinnJeAktie": 5.686,
   "dividende": 3.7338,
   "divRendite": 3.05,
   "sektor": "Konsum",
   "land": "USA"
  },
  {
   "id": "mrk",
   "art": "aktie",
   "name": "Merck & Co",
   "kuerzel": "MRK",
   "kurs": 126.61,
   "kursOriginal": 147.53,
   "waehrungOriginal": "USD",
   "kgv": 115.91,
   "gewinnJeAktie": 1.0923,
   "dividende": 2.9247,
   "divRendite": 2.31,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "gs",
   "art": "aktie",
   "name": "Goldman Sachs",
   "kuerzel": "GS",
   "kurs": 882.92,
   "kursOriginal": 1028.78,
   "waehrungOriginal": "USD",
   "kgv": 15.92,
   "gewinnJeAktie": 55.4598,
   "dividende": 17.1286,
   "divRendite": 1.94,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "nflx",
   "art": "aktie",
   "name": "Netflix",
   "kuerzel": "NFLX",
   "kurs": 65.2506,
   "kursOriginal": 76.03,
   "waehrungOriginal": "USD",
   "kgv": 23.95,
   "gewinnJeAktie": 2.7245,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Medien",
   "land": "USA"
  },
  {
   "id": "txn",
   "art": "aktie",
   "name": "Texas Instruments",
   "kuerzel": "TXN",
   "kurs": 224.5,
   "kursOriginal": 261.59,
   "waehrungOriginal": "USD",
   "kgv": 39.74,
   "gewinnJeAktie": 5.6492,
   "dividende": 4.8717,
   "divRendite": 2.17,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "klac",
   "art": "aktie",
   "name": "KLA",
   "kuerzel": "KLAC",
   "kurs": 156.98,
   "kursOriginal": 182.91,
   "waehrungOriginal": "USD",
   "kgv": 49.98,
   "gewinnJeAktie": 3.1409,
   "dividende": 0.7849,
   "divRendite": 0.5,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "axp",
   "art": "aktie",
   "name": "American Express",
   "kuerzel": "AXP",
   "kurs": 276.18,
   "kursOriginal": 321.8,
   "waehrungOriginal": "USD",
   "kgv": 19.54,
   "gewinnJeAktie": 14.1341,
   "dividende": 3.2589,
   "divRendite": 1.18,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "panw",
   "art": "aktie",
   "name": "Palo Alto Networks",
   "kuerzel": "PANW",
   "kurs": 287.59,
   "kursOriginal": 335.1,
   "waehrungOriginal": "USD",
   "kgv": 889.6,
   "gewinnJeAktie": 0.32328,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "intc",
   "art": "aktie",
   "name": "Intel",
   "kuerzel": "INTC",
   "kurs": 91.1775,
   "kursOriginal": 106.24,
   "waehrungOriginal": "USD",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "ma",
   "art": "aktie",
   "name": "Mastercard",
   "kuerzel": "MA",
   "kurs": 487.04,
   "kursOriginal": 567.5,
   "waehrungOriginal": "USD",
   "kgv": 31.21,
   "gewinnJeAktie": 15.6053,
   "dividende": 2.9709,
   "divRendite": 0.61,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "lly",
   "art": "aktie",
   "name": "Eli Lilly",
   "kuerzel": "LLY",
   "kurs": 964.82,
   "kursOriginal": 1124.21,
   "waehrungOriginal": "USD",
   "kgv": 37.74,
   "gewinnJeAktie": 25.5649,
   "dividende": 5.9819,
   "divRendite": 0.62,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "xom",
   "art": "aktie",
   "name": "ExxonMobil",
   "kuerzel": "XOM",
   "kurs": 140.95,
   "kursOriginal": 164.23,
   "waehrungOriginal": "USD",
   "kgv": 21.17,
   "gewinnJeAktie": 6.658,
   "dividende": 3.5378,
   "divRendite": 2.51,
   "sektor": "Energie",
   "land": "USA"
  },
  {
   "id": "orcl",
   "art": "aktie",
   "name": "Oracle",
   "kuerzel": "ORCL",
   "kurs": 138.71,
   "kursOriginal": 161.63,
   "waehrungOriginal": "USD",
   "kgv": 27.72,
   "gewinnJeAktie": 5.004,
   "dividende": 1.72,
   "divRendite": 1.24,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "ge",
   "art": "aktie",
   "name": "GE Aerospace",
   "kuerzel": "GE",
   "kurs": 279.28,
   "kursOriginal": 325.42,
   "waehrungOriginal": "USD",
   "kgv": 38.36,
   "gewinnJeAktie": 7.2805,
   "dividende": 1.6198,
   "divRendite": 0.58,
   "sektor": "Luftfahrt",
   "land": "USA"
  },
  {
   "id": "bac",
   "art": "aktie",
   "name": "Bank of America",
   "kuerzel": "BAC",
   "kurs": 53.7848,
   "kursOriginal": 62.67,
   "waehrungOriginal": "USD",
   "kgv": 14.48,
   "gewinnJeAktie": 3.7144,
   "dividende": 1.0972,
   "divRendite": 2.04,
   "sektor": "Banken",
   "land": "USA"
  },
  {
   "id": "tsm",
   "art": "aktie",
   "name": "TSMC",
   "kuerzel": "TSM",
   "kurs": 373.64,
   "kursOriginal": 435.36,
   "waehrungOriginal": "USD",
   "kgv": 29.12,
   "gewinnJeAktie": 12.831,
   "dividende": 2.7649,
   "divRendite": 0.74,
   "sektor": "Halbleiter",
   "land": "Taiwan"
  },
  {
   "id": "skhy",
   "art": "aktie",
   "name": "SK hynix",
   "kuerzel": "SKHY",
   "kurs": 1194.01,
   "kursOriginal": 1859000,
   "waehrungOriginal": "KRW",
   "kgv": 8.14,
   "gewinnJeAktie": 146.68,
   "dividende": 2.2686,
   "divRendite": 0.19,
   "sektor": "Halbleiter",
   "land": "Suedkorea"
  },
  {
   "id": "baba",
   "art": "aktie",
   "name": "Alibaba",
   "kuerzel": "BABA",
   "kurs": 93.8895,
   "kursOriginal": 109.4,
   "waehrungOriginal": "USD",
   "kgv": 24.97,
   "gewinnJeAktie": 3.7601,
   "dividende": 0.901339,
   "divRendite": 0.96,
   "sektor": "Handel",
   "land": "China"
  },
  {
   "id": "mufg",
   "art": "aktie",
   "name": "Mitsubishi UFJ",
   "kuerzel": "MUFG",
   "kurs": 19.8593,
   "kursOriginal": 23.14,
   "waehrungOriginal": "USD",
   "kgv": 21.89,
   "gewinnJeAktie": 0.907232,
   "dividende": 0.379313,
   "divRendite": 1.91,
   "sektor": "Banken",
   "land": "Japan"
  },
  {
   "id": "arm",
   "art": "aktie",
   "name": "Arm Holdings",
   "kuerzel": "ARM",
   "kurs": 226.77,
   "kursOriginal": 264.23,
   "waehrungOriginal": "USD",
   "kgv": 269.71,
   "gewinnJeAktie": 0.840792,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Halbleiter",
   "land": "Grossbritannien"
  },
  {
   "id": "shel",
   "art": "aktie",
   "name": "Shell",
   "kuerzel": "SHEL",
   "kurs": 82.046,
   "kursOriginal": 95.6,
   "waehrungOriginal": "USD",
   "kgv": 10.51,
   "gewinnJeAktie": 7.8065,
   "dividende": 2.5927,
   "divRendite": 3.16,
   "sektor": "Energie",
   "land": "Grossbritannien"
  },
  {
   "id": "azn",
   "art": "aktie",
   "name": "AstraZeneca",
   "kuerzel": "AZN",
   "kurs": 134.69,
   "kursOriginal": 156.94,
   "waehrungOriginal": "USD",
   "kgv": 23.43,
   "gewinnJeAktie": 5.7486,
   "dividende": 2.7746,
   "divRendite": 2.06,
   "sektor": "Pharma",
   "land": "Grossbritannien"
  },
  {
   "id": "hsbc",
   "art": "aktie",
   "name": "HSBC",
   "kuerzel": "HSBC",
   "kurs": 90.2077,
   "kursOriginal": 105.11,
   "waehrungOriginal": "USD",
   "kgv": 17.04,
   "gewinnJeAktie": 5.2939,
   "dividende": 3.2024,
   "divRendite": 3.55,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "nvs",
   "art": "aktie",
   "name": "Novartis",
   "kuerzel": "NVS",
   "kurs": 117.99,
   "kursOriginal": 137.48,
   "waehrungOriginal": "USD",
   "kgv": 20.53,
   "gewinnJeAktie": 5.7472,
   "dividende": 2.643,
   "divRendite": 2.24,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "ry",
   "art": "aktie",
   "name": "Royal Bank of Canada",
   "kuerzel": "RY",
   "kurs": 177.49,
   "kursOriginal": 206.81,
   "waehrungOriginal": "USD",
   "kgv": 18.29,
   "gewinnJeAktie": 9.7042,
   "dividende": 4.2243,
   "divRendite": 2.38,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "p911",
   "art": "aktie",
   "name": "Porsche AG",
   "kuerzel": "P911",
   "kurs": 45.27,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 48.49,
   "gewinnJeAktie": 0.933595,
   "dividende": 1.014,
   "divRendite": 2.24,
   "sektor": "Automobil",
   "land": "Deutschland"
  },
  {
   "id": "fre",
   "art": "aktie",
   "name": "Fresenius",
   "kuerzel": "FRE",
   "kurs": 44.5,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 15.98,
   "gewinnJeAktie": 2.7847,
   "dividende": 1.0458,
   "divRendite": 2.35,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "fme",
   "art": "aktie",
   "name": "Fresenius Medical Care",
   "kuerzel": "FME",
   "kurs": 38.8,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.52,
   "gewinnJeAktie": 3.3681,
   "dividende": 1.4899,
   "divRendite": 3.84,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "sy1",
   "art": "aktie",
   "name": "Symrise",
   "kuerzel": "SY1",
   "kurs": 88.2,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 50.17,
   "gewinnJeAktie": 1.758,
   "dividende": 1.2083,
   "divRendite": 1.37,
   "sektor": "Chemie",
   "land": "Deutschland"
  },
  {
   "id": "srt3",
   "art": "aktie",
   "name": "Sartorius Vorzuege",
   "kuerzel": "SRT3",
   "kurs": 235.4,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 74.92,
   "gewinnJeAktie": 3.142,
   "dividende": 0.7062,
   "divRendite": 0.3,
   "sektor": "Gesundheit",
   "land": "Deutschland"
  },
  {
   "id": "tlx",
   "art": "aktie",
   "name": "Talanx",
   "kuerzel": "TLX",
   "kurs": 120.3,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 11.83,
   "gewinnJeAktie": 10.1691,
   "dividende": 3.4045,
   "divRendite": 2.83,
   "sektor": "Versicherung",
   "land": "Deutschland"
  },
  {
   "id": "pub",
   "art": "aktie",
   "name": "Publicis Groupe",
   "kuerzel": "PUB",
   "kurs": 96.36,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.96,
   "gewinnJeAktie": 6.4412,
   "dividende": 3.546,
   "divRendite": 3.68,
   "sektor": "Medien",
   "land": "Frankreich"
  },
  {
   "id": "stla",
   "art": "aktie",
   "name": "Stellantis",
   "kuerzel": "STLA",
   "kurs": 4.5685,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Automobil",
   "land": "Niederlande"
  },
  {
   "id": "prx",
   "art": "aktie",
   "name": "Prosus",
   "kuerzel": "PRX",
   "kurs": 35.635,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 7.88,
   "gewinnJeAktie": 4.5222,
   "dividende": 0.270826,
   "divRendite": 0.76,
   "sektor": "Technologie",
   "land": "Niederlande"
  },
  {
   "id": "g",
   "art": "aktie",
   "name": "Generali",
   "kuerzel": "G",
   "kurs": 44.53,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 15.1,
   "gewinnJeAktie": 2.949,
   "dividende": 1.6565,
   "divRendite": 3.72,
   "sektor": "Versicherung",
   "land": "Italien"
  },
  {
   "id": "bbva",
   "art": "aktie",
   "name": "BBVA",
   "kuerzel": "BBVA",
   "kurs": 24.93,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 13.24,
   "gewinnJeAktie": 1.8829,
   "dividende": 0.902466,
   "divRendite": 3.62,
   "sektor": "Banken",
   "land": "Spanien"
  },
  {
   "id": "tef",
   "art": "aktie",
   "name": "Telefonica",
   "kuerzel": "TEF",
   "kurs": 3.61,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.295659,
   "divRendite": 8.19,
   "sektor": "Telekom",
   "land": "Spanien"
  },
  {
   "id": "kbc",
   "art": "aktie",
   "name": "KBC Group",
   "kuerzel": "KBC",
   "kurs": 129.9,
   "kursOriginal": null,
   "waehrungOriginal": null,
   "kgv": 14.52,
   "gewinnJeAktie": 8.9463,
   "dividende": 4.9622,
   "divRendite": 3.82,
   "sektor": "Banken",
   "land": "Belgien"
  },
  {
   "id": "ulvr",
   "art": "aktie",
   "name": "Unilever",
   "kuerzel": "ULVR",
   "kurs": 53.5344,
   "kursOriginal": 4598.5,
   "waehrungOriginal": "GBX",
   "kgv": 21.05,
   "gewinnJeAktie": 2.5432,
   "dividende": 1.9433,
   "divRendite": 3.63,
   "sektor": "Konsum",
   "land": "Grossbritannien"
  },
  {
   "id": "bp1",
   "art": "aktie",
   "name": "BP",
   "kuerzel": "BP1",
   "kurs": 6.545,
   "kursOriginal": 562.2,
   "waehrungOriginal": "GBX",
   "kgv": 21.44,
   "gewinnJeAktie": 0.305271,
   "dividende": 0.299106,
   "divRendite": 4.57,
   "sektor": "Energie",
   "land": "Grossbritannien"
  },
  {
   "id": "gsk",
   "art": "aktie",
   "name": "GSK",
   "kuerzel": "GSK",
   "kurs": 20.8387,
   "kursOriginal": 1790,
   "waehrungOriginal": "GBX",
   "kgv": 15.3,
   "gewinnJeAktie": 1.362,
   "dividende": 0.806458,
   "divRendite": 3.87,
   "sektor": "Pharma",
   "land": "Grossbritannien"
  },
  {
   "id": "dge",
   "art": "aktie",
   "name": "Diageo",
   "kuerzel": "DGE",
   "kurs": 18.4347,
   "kursOriginal": 1583.5,
   "waehrungOriginal": "GBX",
   "kgv": 27.22,
   "gewinnJeAktie": 0.677248,
   "dividende": 0.40925,
   "divRendite": 2.22,
   "sektor": "Nahrung",
   "land": "Grossbritannien"
  },
  {
   "id": "rio",
   "art": "aktie",
   "name": "Rio Tinto",
   "kuerzel": "RIO",
   "kurs": 87.7785,
   "kursOriginal": 7540,
   "waehrungOriginal": "GBX",
   "kgv": 13.66,
   "gewinnJeAktie": 6.426,
   "dividende": 3.4321,
   "divRendite": 3.91,
   "sektor": "Industrie",
   "land": "Grossbritannien"
  },
  {
   "id": "barc",
   "art": "aktie",
   "name": "Barclays",
   "kuerzel": "BARC",
   "kurs": 5.6619,
   "kursOriginal": 486.35,
   "waehrungOriginal": "GBX",
   "kgv": 10.14,
   "gewinnJeAktie": 0.558373,
   "dividende": 0.0985171,
   "divRendite": 1.74,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "lloy",
   "art": "aktie",
   "name": "Lloyds Banking Group",
   "kuerzel": "LLOY",
   "kurs": 1.2759,
   "kursOriginal": 109.6,
   "waehrungOriginal": "GBX",
   "kgv": 13.74,
   "gewinnJeAktie": 0.0928603,
   "dividende": 0.0419771,
   "divRendite": 3.29,
   "sektor": "Banken",
   "land": "Grossbritannien"
  },
  {
   "id": "ba1",
   "art": "aktie",
   "name": "BAE Systems",
   "kuerzel": "BA1",
   "kurs": 22.1658,
   "kursOriginal": 1904,
   "waehrungOriginal": "GBX",
   "kgv": 27.2,
   "gewinnJeAktie": 0.814919,
   "dividende": 0.00443316,
   "divRendite": 0.02,
   "sektor": "Ruestung",
   "land": "Grossbritannien"
  },
  {
   "id": "rr",
   "art": "aktie",
   "name": "Rolls-Royce",
   "kuerzel": "RR",
   "kurs": 16.6593,
   "kursOriginal": 1431,
   "waehrungOriginal": "GBX",
   "kgv": 39.96,
   "gewinnJeAktie": 0.416899,
   "dividende": 0.13494,
   "divRendite": 0.81,
   "sektor": "Luftfahrt",
   "land": "Grossbritannien"
  },
  {
   "id": "nesn",
   "art": "aktie",
   "name": "Nestle",
   "kuerzel": "NESN",
   "kurs": 82.4968,
   "kursOriginal": 77.58,
   "waehrungOriginal": "CHF",
   "kgv": 26.88,
   "gewinnJeAktie": 3.0691,
   "dividende": 3.2504,
   "divRendite": 3.94,
   "sektor": "Nahrung",
   "land": "Schweiz"
  },
  {
   "id": "ro",
   "art": "aktie",
   "name": "Roche",
   "kuerzel": "RO",
   "kurs": 374.52,
   "kursOriginal": 352.2,
   "waehrungOriginal": "CHF",
   "kgv": 22.52,
   "gewinnJeAktie": 16.6306,
   "dividende": 11.4603,
   "divRendite": 3.06,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "zurn",
   "art": "aktie",
   "name": "Zurich Insurance",
   "kuerzel": "ZURN",
   "kurs": 623.35,
   "kursOriginal": 586.20001,
   "waehrungOriginal": "CHF",
   "kgv": 14.68,
   "gewinnJeAktie": 42.4625,
   "dividende": 30.9182,
   "divRendite": 4.96,
   "sektor": "Versicherung",
   "land": "Schweiz"
  },
  {
   "id": "abbn",
   "art": "aktie",
   "name": "ABB",
   "kuerzel": "ABBN",
   "kurs": 83.3475,
   "kursOriginal": 78.38,
   "waehrungOriginal": "CHF",
   "kgv": 35.63,
   "gewinnJeAktie": 2.3393,
   "dividende": 1.0168,
   "divRendite": 1.22,
   "sektor": "Industrie",
   "land": "Schweiz"
  },
  {
   "id": "ubsg",
   "art": "aktie",
   "name": "UBS Group",
   "kuerzel": "UBSG",
   "kurs": 47.3947,
   "kursOriginal": 44.57,
   "waehrungOriginal": "CHF",
   "kgv": 18.8,
   "gewinnJeAktie": 2.521,
   "dividende": 0.943155,
   "divRendite": 1.99,
   "sektor": "Banken",
   "land": "Schweiz"
  },
  {
   "id": "cfr",
   "art": "aktie",
   "name": "Richemont",
   "kuerzel": "CFR",
   "kurs": 183.96,
   "kursOriginal": 173,
   "waehrungOriginal": "CHF",
   "kgv": 32.23,
   "gewinnJeAktie": 5.7077,
   "dividende": 3.3113,
   "divRendite": 1.8,
   "sektor": "Luxus",
   "land": "Schweiz"
  },
  {
   "id": "holn",
   "art": "aktie",
   "name": "Holcim",
   "kuerzel": "HOLN",
   "kurs": 75.6912,
   "kursOriginal": 71.18,
   "waehrungOriginal": "CHF",
   "kgv": 101.65,
   "gewinnJeAktie": 0.744626,
   "dividende": 1.7939,
   "divRendite": 2.37,
   "sektor": "Bau",
   "land": "Schweiz"
  },
  {
   "id": "sika",
   "art": "aktie",
   "name": "Sika",
   "kuerzel": "SIKA",
   "kurs": 199.44,
   "kursOriginal": 187.55,
   "waehrungOriginal": "CHF",
   "kgv": 29,
   "gewinnJeAktie": 6.8772,
   "dividende": 3.929,
   "divRendite": 1.97,
   "sektor": "Chemie",
   "land": "Schweiz"
  },
  {
   "id": "sren",
   "art": "aktie",
   "name": "Swiss Re",
   "kuerzel": "SREN",
   "kurs": 144.51,
   "kursOriginal": 135.9,
   "waehrungOriginal": "CHF",
   "kgv": 10.13,
   "gewinnJeAktie": 14.2655,
   "dividende": 6.6186,
   "divRendite": 4.58,
   "sektor": "Versicherung",
   "land": "Schweiz"
  },
  {
   "id": "lonn",
   "art": "aktie",
   "name": "Lonza",
   "kuerzel": "LONN",
   "kurs": 577.2,
   "kursOriginal": 542.79999,
   "waehrungOriginal": "CHF",
   "kgv": 34.78,
   "gewinnJeAktie": 16.5957,
   "dividende": 5.0216,
   "divRendite": 0.87,
   "sektor": "Pharma",
   "land": "Schweiz"
  },
  {
   "id": "7203",
   "art": "aktie",
   "name": "Toyota Motor",
   "kuerzel": "7203",
   "kurs": 16.7647,
   "kursOriginal": 2994,
   "waehrungOriginal": "JPY",
   "kgv": 8.5,
   "gewinnJeAktie": 1.9723,
   "dividende": 0.544853,
   "divRendite": 3.25,
   "sektor": "Automobil",
   "land": "Japan"
  },
  {
   "id": "6758",
   "art": "aktie",
   "name": "Sony Group",
   "kuerzel": "6758",
   "kurs": 20.3819,
   "kursOriginal": 3640,
   "waehrungOriginal": "JPY",
   "kgv": 19.35,
   "gewinnJeAktie": 1.0533,
   "dividende": 0.195666,
   "divRendite": 0.96,
   "sektor": "Technologie",
   "land": "Japan"
  },
  {
   "id": "7974",
   "art": "aktie",
   "name": "Nintendo",
   "kuerzel": "7974",
   "kurs": 44.7337,
   "kursOriginal": 7989,
   "waehrungOriginal": "JPY",
   "kgv": 20.51,
   "gewinnJeAktie": 2.1811,
   "dividende": 0.818627,
   "divRendite": 1.83,
   "sektor": "Medien",
   "land": "Japan"
  },
  {
   "id": "6861",
   "art": "aktie",
   "name": "Keyence",
   "kuerzel": "6861",
   "kurs": 428.36,
   "kursOriginal": 76500,
   "waehrungOriginal": "JPY",
   "kgv": 37.59,
   "gewinnJeAktie": 11.3956,
   "dividende": 3.0414,
   "divRendite": 0.71,
   "sektor": "Industrie",
   "land": "Japan"
  },
  {
   "id": "8035",
   "art": "aktie",
   "name": "Tokyo Electron",
   "kuerzel": "8035",
   "kurs": 295.71,
   "kursOriginal": 52810,
   "waehrungOriginal": "JPY",
   "kgv": 38.99,
   "gewinnJeAktie": 7.5843,
   "dividende": 4.1399,
   "divRendite": 1.4,
   "sektor": "Halbleiter",
   "land": "Japan"
  },
  {
   "id": "6857",
   "art": "aktie",
   "name": "Advantest",
   "kuerzel": "6857",
   "kurs": 189.93,
   "kursOriginal": 33920,
   "waehrungOriginal": "JPY",
   "kgv": 52.11,
   "gewinnJeAktie": 3.6448,
   "dividende": 0.341874,
   "divRendite": 0.18,
   "sektor": "Halbleiter",
   "land": "Japan"
  },
  {
   "id": "9984",
   "art": "aktie",
   "name": "SoftBank Group",
   "kuerzel": "9984",
   "kurs": 38.132,
   "kursOriginal": 6810,
   "waehrungOriginal": "JPY",
   "kgv": 7.92,
   "gewinnJeAktie": 4.8146,
   "dividende": 0.0838904,
   "divRendite": 0.22,
   "sektor": "Technologie",
   "land": "Japan"
  },
  {
   "id": "6501",
   "art": "aktie",
   "name": "Hitachi",
   "kuerzel": "6501",
   "kurs": 29.0162,
   "kursOriginal": 5182,
   "waehrungOriginal": "JPY",
   "kgv": 29.29,
   "gewinnJeAktie": 0.990652,
   "dividende": 0.30467,
   "divRendite": 1.05,
   "sektor": "Industrie",
   "land": "Japan"
  },
  {
   "id": "8058",
   "art": "aktie",
   "name": "Mitsubishi Corporation",
   "kuerzel": "8058",
   "kurs": 27.9243,
   "kursOriginal": 4987,
   "waehrungOriginal": "JPY",
   "kgv": 21.07,
   "gewinnJeAktie": 1.3253,
   "dividende": 0.684145,
   "divRendite": 2.45,
   "sektor": "Handel",
   "land": "Japan"
  },
  {
   "id": "4063",
   "art": "aktie",
   "name": "Shin-Etsu Chemical",
   "kuerzel": "4063",
   "kurs": 32.2638,
   "kursOriginal": 5762,
   "waehrungOriginal": "JPY",
   "kgv": 22.49,
   "gewinnJeAktie": 1.4346,
   "dividende": 0.648502,
   "divRendite": 2.01,
   "sektor": "Chemie",
   "land": "Japan"
  },
  {
   "id": "4502",
   "art": "aktie",
   "name": "Takeda Pharmaceutical",
   "kuerzel": "4502",
   "kurs": 31.6759,
   "kursOriginal": 5657,
   "waehrungOriginal": "JPY",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 1.0928,
   "divRendite": 3.45,
   "sektor": "Pharma",
   "land": "Japan"
  },
  {
   "id": "7267",
   "art": "aktie",
   "name": "Honda Motor",
   "kuerzel": "7267",
   "kurs": 9.1522,
   "kursOriginal": 1634.5,
   "waehrungOriginal": "JPY",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0.377986,
   "divRendite": 4.13,
   "sektor": "Automobil",
   "land": "Japan"
  },
  {
   "id": "8316",
   "art": "aktie",
   "name": "Sumitomo Mitsui Financial",
   "kuerzel": "8316",
   "kurs": 38.6416,
   "kursOriginal": 6901,
   "waehrungOriginal": "JPY",
   "kgv": 20.63,
   "gewinnJeAktie": 1.8731,
   "dividende": 0.981497,
   "divRendite": 2.54,
   "sektor": "Banken",
   "land": "Japan"
  },
  {
   "id": "9983",
   "art": "aktie",
   "name": "Fast Retailing",
   "kuerzel": "9983",
   "kurs": 374.1,
   "kursOriginal": 66810,
   "waehrungOriginal": "JPY",
   "kgv": 39.51,
   "gewinnJeAktie": 9.4685,
   "dividende": 3.4417,
   "divRendite": 0.92,
   "sektor": "Handel",
   "land": "Japan"
  },
  {
   "id": "9432",
   "art": "aktie",
   "name": "Nippon Telegraph & Telephone",
   "kuerzel": "9432",
   "kurs": 0.981018,
   "kursOriginal": 175.2,
   "waehrungOriginal": "JPY",
   "kgv": 13.6,
   "gewinnJeAktie": 0.0721337,
   "dividende": 0.0302154,
   "divRendite": 3.08,
   "sektor": "Telekom",
   "land": "Japan"
  },
  {
   "id": "005930",
   "art": "aktie",
   "name": "Samsung Electronics",
   "kuerzel": "005930",
   "kurs": 172.94,
   "kursOriginal": 269250,
   "waehrungOriginal": "KRW",
   "kgv": 12.02,
   "gewinnJeAktie": 14.3877,
   "dividende": 1.5392,
   "divRendite": 0.89,
   "sektor": "Technologie",
   "land": "Suedkorea"
  },
  {
   "id": "005380",
   "art": "aktie",
   "name": "Hyundai Motor",
   "kuerzel": "005380",
   "kurs": 249.85,
   "kursOriginal": 389000,
   "waehrungOriginal": "KRW",
   "kgv": 12.45,
   "gewinnJeAktie": 20.0683,
   "dividende": 6.5211,
   "divRendite": 2.61,
   "sektor": "Automobil",
   "land": "Suedkorea"
  },
  {
   "id": "000270",
   "art": "aktie",
   "name": "Kia",
   "kuerzel": "000270",
   "kurs": 81.5703,
   "kursOriginal": 127000,
   "waehrungOriginal": "KRW",
   "kgv": 6.99,
   "gewinnJeAktie": 11.6696,
   "dividende": 4.3559,
   "divRendite": 5.34,
   "sektor": "Automobil",
   "land": "Suedkorea"
  },
  {
   "id": "035420",
   "art": "aktie",
   "name": "NAVER",
   "kuerzel": "035420",
   "kurs": 133.6,
   "kursOriginal": 208000,
   "waehrungOriginal": "KRW",
   "kgv": 15.68,
   "gewinnJeAktie": 8.5204,
   "dividende": 1.6967,
   "divRendite": 1.27,
   "sektor": "Technologie",
   "land": "Suedkorea"
  },
  {
   "id": "207940",
   "art": "aktie",
   "name": "Samsung Biologics",
   "kuerzel": "207940",
   "kurs": 913.97,
   "kursOriginal": 1423000,
   "waehrungOriginal": "KRW",
   "kgv": 33.52,
   "gewinnJeAktie": 27.2664,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Pharma",
   "land": "Suedkorea"
  },
  {
   "id": "005490",
   "art": "aktie",
   "name": "POSCO Holdings",
   "kuerzel": "005490",
   "kurs": 217.73,
   "kursOriginal": 339000,
   "waehrungOriginal": "KRW",
   "kgv": 18.91,
   "gewinnJeAktie": 11.514,
   "dividende": 5.182,
   "divRendite": 2.38,
   "sektor": "Industrie",
   "land": "Suedkorea"
  },
  {
   "id": "373220",
   "art": "aktie",
   "name": "LG Energy Solution",
   "kuerzel": "373220",
   "kurs": 234.43,
   "kursOriginal": 365000,
   "waehrungOriginal": "KRW",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Industrie",
   "land": "Suedkorea"
  },
  {
   "id": "0700",
   "art": "aktie",
   "name": "Tencent Holdings",
   "kuerzel": "0700",
   "kurs": 46.5758,
   "kursOriginal": 425.6,
   "waehrungOriginal": "HKD",
   "kgv": 14.77,
   "gewinnJeAktie": 3.1534,
   "dividende": 0.568225,
   "divRendite": 1.22,
   "sektor": "Technologie",
   "land": "Hongkong"
  },
  {
   "id": "1299",
   "art": "aktie",
   "name": "AIA Group",
   "kuerzel": "1299",
   "kurs": 8.2405,
   "kursOriginal": 75.3,
   "waehrungOriginal": "HKD",
   "kgv": 12.84,
   "gewinnJeAktie": 0.641783,
   "dividende": 0.206013,
   "divRendite": 2.5,
   "sektor": "Versicherung",
   "land": "Hongkong"
  },
  {
   "id": "0388",
   "art": "aktie",
   "name": "Hong Kong Exchanges",
   "kuerzel": "0388",
   "kurs": 43.4459,
   "kursOriginal": 397,
   "waehrungOriginal": "HKD",
   "kgv": 25.62,
   "gewinnJeAktie": 1.6958,
   "dividende": 1.5597,
   "divRendite": 3.59,
   "sektor": "Finanzen",
   "land": "Hongkong"
  },
  {
   "id": "shop",
   "art": "aktie",
   "name": "Shopify",
   "kuerzel": "SHOP",
   "kurs": 109.16,
   "kursOriginal": 175.13,
   "waehrungOriginal": "CAD",
   "kgv": 82.3,
   "gewinnJeAktie": 1.3264,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "Kanada"
  },
  {
   "id": "td",
   "art": "aktie",
   "name": "Toronto-Dominion Bank",
   "kuerzel": "TD",
   "kurs": 102.66,
   "kursOriginal": 164.7,
   "waehrungOriginal": "CAD",
   "kgv": 17.7,
   "gewinnJeAktie": 5.8,
   "dividende": 2.7924,
   "divRendite": 2.72,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "bns",
   "art": "aktie",
   "name": "Bank of Nova Scotia",
   "kuerzel": "BNS",
   "kurs": 79.343,
   "kursOriginal": 127.29,
   "waehrungOriginal": "CAD",
   "kgv": 16.63,
   "gewinnJeAktie": 4.7711,
   "dividende": 2.8246,
   "divRendite": 3.56,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "bmo",
   "art": "aktie",
   "name": "Bank of Montreal",
   "kuerzel": "BMO",
   "kurs": 148.55,
   "kursOriginal": 238.32,
   "waehrungOriginal": "CAD",
   "kgv": 19.42,
   "gewinnJeAktie": 7.6493,
   "dividende": 4.1743,
   "divRendite": 2.81,
   "sektor": "Banken",
   "land": "Kanada"
  },
  {
   "id": "enb",
   "art": "aktie",
   "name": "Enbridge",
   "kuerzel": "ENB",
   "kurs": 43.1839,
   "kursOriginal": 69.28,
   "waehrungOriginal": "CAD",
   "kgv": 26.75,
   "gewinnJeAktie": 1.6144,
   "dividende": 2.4183,
   "divRendite": 5.6,
   "sektor": "Energie",
   "land": "Kanada"
  },
  {
   "id": "cnq",
   "art": "aktie",
   "name": "Canadian Natural Resources",
   "kuerzel": "CNQ",
   "kurs": 44.1937,
   "kursOriginal": 70.9,
   "waehrungOriginal": "CAD",
   "kgv": 12.61,
   "gewinnJeAktie": 3.5047,
   "dividende": 1.56,
   "divRendite": 3.53,
   "sektor": "Energie",
   "land": "Kanada"
  },
  {
   "id": "cnr",
   "art": "aktie",
   "name": "Canadian National Railway",
   "kuerzel": "CNR",
   "kurs": 104.94,
   "kursOriginal": 168.35,
   "waehrungOriginal": "CAD",
   "kgv": 21.61,
   "gewinnJeAktie": 4.8561,
   "dividende": 2.2667,
   "divRendite": 2.16,
   "sektor": "Logistik",
   "land": "Kanada"
  },
  {
   "id": "cp",
   "art": "aktie",
   "name": "Canadian Pacific Kansas City",
   "kuerzel": "CP",
   "kurs": 77.579,
   "kursOriginal": 124.46,
   "waehrungOriginal": "CAD",
   "kgv": 28.95,
   "gewinnJeAktie": 2.6798,
   "dividende": 0.659421,
   "divRendite": 0.85,
   "sektor": "Logistik",
   "land": "Kanada"
  },
  {
   "id": "bce",
   "art": "aktie",
   "name": "BCE",
   "kuerzel": "BCE",
   "kurs": 20.1022,
   "kursOriginal": 32.25,
   "waehrungOriginal": "CAD",
   "kgv": 4.8,
   "gewinnJeAktie": 4.188,
   "dividende": 1.0714,
   "divRendite": 5.33,
   "sektor": "Telekom",
   "land": "Kanada"
  },
  {
   "id": "bn1",
   "art": "aktie",
   "name": "Brookfield Corporation",
   "kuerzel": "BN1",
   "kurs": 33.192,
   "kursOriginal": 53.25,
   "waehrungOriginal": "CAD",
   "kgv": 69.76,
   "gewinnJeAktie": 0.475803,
   "dividende": 0.229025,
   "divRendite": 0.69,
   "sektor": "Finanzen",
   "land": "Kanada"
  },
  {
   "id": "ba",
   "art": "aktie",
   "name": "Boeing",
   "kuerzel": "BA",
   "kurs": 177.15,
   "kursOriginal": 206.42,
   "waehrungOriginal": "USD",
   "kgv": 76.98,
   "gewinnJeAktie": 2.3012,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Luftfahrt",
   "land": "USA"
  },
  {
   "id": "dis",
   "art": "aktie",
   "name": "Walt Disney",
   "kuerzel": "DIS",
   "kurs": 89.4095,
   "kursOriginal": 104.18,
   "waehrungOriginal": "USD",
   "kgv": 21.54,
   "gewinnJeAktie": 4.1509,
   "dividende": 1.2875,
   "divRendite": 1.44,
   "sektor": "Medien",
   "land": "USA"
  },
  {
   "id": "vz",
   "art": "aktie",
   "name": "Verizon Communications",
   "kuerzel": "VZ",
   "kurs": 42.688,
   "kursOriginal": 49.74,
   "waehrungOriginal": "USD",
   "kgv": 12.96,
   "gewinnJeAktie": 3.2938,
   "dividende": 2.4289,
   "divRendite": 5.69,
   "sektor": "Telekom",
   "land": "USA"
  },
  {
   "id": "lmt",
   "art": "aktie",
   "name": "Lockheed Martin",
   "kuerzel": "LMT",
   "kurs": 450.1,
   "kursOriginal": 524.46,
   "waehrungOriginal": "USD",
   "kgv": 19.33,
   "gewinnJeAktie": 23.285,
   "dividende": 11.8376,
   "divRendite": 2.63,
   "sektor": "Ruestung",
   "land": "USA"
  },
  {
   "id": "amt",
   "art": "aktie",
   "name": "American Tower",
   "kuerzel": "AMT",
   "kurs": 150.56,
   "kursOriginal": 175.43,
   "waehrungOriginal": "USD",
   "kgv": 24.13,
   "gewinnJeAktie": 6.2395,
   "dividende": 6.1428,
   "divRendite": 4.08,
   "sektor": "Immobilien",
   "land": "USA"
  },
  {
   "id": "crm",
   "art": "aktie",
   "name": "Salesforce",
   "kuerzel": "CRM",
   "kurs": 209.54,
   "kursOriginal": 244.16,
   "waehrungOriginal": "USD",
   "kgv": 22.63,
   "gewinnJeAktie": 9.2594,
   "dividende": 1.5087,
   "divRendite": 0.72,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "adbe",
   "art": "aktie",
   "name": "Adobe",
   "kuerzel": "ADBE",
   "kurs": 218.73,
   "kursOriginal": 254.86,
   "waehrungOriginal": "USD",
   "kgv": 14.58,
   "gewinnJeAktie": 15.0021,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "qcom",
   "art": "aktie",
   "name": "Qualcomm",
   "kuerzel": "QCOM",
   "kurs": 151.39,
   "kursOriginal": 176.4,
   "waehrungOriginal": "USD",
   "kgv": 20.53,
   "gewinnJeAktie": 7.3741,
   "dividende": 3.1641,
   "divRendite": 2.09,
   "sektor": "Halbleiter",
   "land": "USA"
  },
  {
   "id": "ibm",
   "art": "aktie",
   "name": "IBM",
   "kuerzel": "IBM",
   "kurs": 205.92,
   "kursOriginal": 239.94,
   "waehrungOriginal": "USD",
   "kgv": 21.33,
   "gewinnJeAktie": 9.654,
   "dividende": 5.8069,
   "divRendite": 2.82,
   "sektor": "Technologie",
   "land": "USA"
  },
  {
   "id": "pfe",
   "art": "aktie",
   "name": "Pfizer",
   "kuerzel": "PFE",
   "kurs": 23.8414,
   "kursOriginal": 27.78,
   "waehrungOriginal": "USD",
   "kgv": 36.52,
   "gewinnJeAktie": 0.652831,
   "dividende": 1.4758,
   "divRendite": 6.19,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "abbv",
   "art": "aktie",
   "name": "AbbVie",
   "kuerzel": "ABBV",
   "kurs": 215.34,
   "kursOriginal": 250.91,
   "waehrungOriginal": "USD",
   "kgv": 70.88,
   "gewinnJeAktie": 3.0381,
   "dividende": 5.9434,
   "divRendite": 2.76,
   "sektor": "Pharma",
   "land": "USA"
  },
  {
   "id": "mcd",
   "art": "aktie",
   "name": "McDonald's",
   "kuerzel": "MCD",
   "kurs": 217.54,
   "kursOriginal": 253.48,
   "waehrungOriginal": "USD",
   "kgv": 20.59,
   "gewinnJeAktie": 10.5653,
   "dividende": 6.3957,
   "divRendite": 2.94,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "nke",
   "art": "aktie",
   "name": "Nike",
   "kuerzel": "NKE",
   "kurs": 32.0546,
   "kursOriginal": 37.35,
   "waehrungOriginal": "USD",
   "kgv": 17.79,
   "gewinnJeAktie": 1.8018,
   "dividende": 1.4072,
   "divRendite": 4.39,
   "sektor": "Konsum",
   "land": "USA"
  },
  {
   "id": "pep",
   "art": "aktie",
   "name": "PepsiCo",
   "kuerzel": "PEP",
   "kurs": 117.31,
   "kursOriginal": 136.69,
   "waehrungOriginal": "USD",
   "kgv": 17.91,
   "gewinnJeAktie": 6.55,
   "dividende": 5.0795,
   "divRendite": 4.33,
   "sektor": "Nahrung",
   "land": "USA"
  },
  {
   "id": "coin",
   "art": "aktie",
   "name": "Coinbase",
   "kuerzel": "COIN",
   "kurs": 149.95,
   "kursOriginal": 174.72,
   "waehrungOriginal": "USD",
   "kgv": null,
   "gewinnJeAktie": null,
   "dividende": 0,
   "divRendite": 0,
   "sektor": "Finanzen",
   "land": "USA"
  },
  {
   "id": "voo",
   "art": "etf",
   "name": "Vanguard S&P 500 ETF",
   "kuerzel": "VOO",
   "kurs": 601.5,
   "kursOriginal": 700.87,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 1070,
   "anzahlPositionen": 518,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "qqq",
   "art": "etf",
   "name": "Invesco QQQ Trust",
   "kuerzel": "QQQ",
   "kurs": 614.75,
   "kursOriginal": 716.31,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 480.4,
   "anzahlPositionen": 105,
   "ter": 0.18,
   "ausschuettend": true,
   "sektor": "USA Technologie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vt",
   "art": "etf",
   "name": "Vanguard Total World Stock ETF",
   "kuerzel": "VT",
   "kurs": 137.22,
   "kursOriginal": 159.89,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 81.8,
   "anzahlPositionen": 10118,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Welt",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vea",
   "art": "etf",
   "name": "Vanguard FTSE Developed Markets ETF",
   "kuerzel": "VEA",
   "kurs": 62.4957,
   "kursOriginal": 72.82,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 240.5,
   "anzahlPositionen": 3877,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Welt ohne USA",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vwo",
   "art": "etf",
   "name": "Vanguard FTSE Emerging Markets ETF",
   "kuerzel": "VWO",
   "kurs": 52.24,
   "kursOriginal": 60.87,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 128.9,
   "anzahlPositionen": 5063,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Schwellenlaender",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "efa",
   "art": "etf",
   "name": "iShares MSCI EAFE ETF",
   "kuerzel": "EFA",
   "kurs": 91.4521,
   "kursOriginal": 106.56,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 79.6,
   "anzahlPositionen": 699,
   "ter": 0.32,
   "ausschuettend": true,
   "sektor": "Europa/Asien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iwm",
   "art": "etf",
   "name": "iShares Russell 2000 ETF",
   "kuerzel": "IWM",
   "kurs": 249.43,
   "kursOriginal": 290.64,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 78.4,
   "anzahlPositionen": 1971,
   "ter": 0.19,
   "ausschuettend": true,
   "sektor": "USA klein",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ijh",
   "art": "etf",
   "name": "iShares Core S&P Mid-Cap ETF",
   "kuerzel": "IJH",
   "kurs": 63.989,
   "kursOriginal": 74.56,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 123.8,
   "anzahlPositionen": 415,
   "ter": 0.05,
   "ausschuettend": true,
   "sektor": "USA mittel",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "dia",
   "art": "etf",
   "name": "SPDR Dow Jones Industrial Average ETF",
   "kuerzel": "DIA",
   "kurs": 449.77,
   "kursOriginal": 524.07,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 45.6,
   "anzahlPositionen": 31,
   "ter": 0.16,
   "ausschuettend": true,
   "sektor": "USA Standard",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "rsp",
   "art": "etf",
   "name": "Invesco S&P 500 Equal Weight ETF",
   "kuerzel": "RSP",
   "kurs": 184.21,
   "kursOriginal": 214.64,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 99.5,
   "anzahlPositionen": 509,
   "ter": 0.2,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vug",
   "art": "etf",
   "name": "Vanguard Growth ETF",
   "kuerzel": "VUG",
   "kurs": 75.2489,
   "kursOriginal": 87.68,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 226.8,
   "anzahlPositionen": 151,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA Wachstum",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vtv",
   "art": "etf",
   "name": "Vanguard Value ETF",
   "kuerzel": "VTV",
   "kurs": 192.17,
   "kursOriginal": 223.92,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 193.8,
   "anzahlPositionen": 324,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA Substanz",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "schd",
   "art": "etf",
   "name": "Schwab US Dividend Equity ETF",
   "kuerzel": "SCHD",
   "kurs": 29.2568,
   "kursOriginal": 34.09,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 112.6,
   "anzahlPositionen": 103,
   "ter": 0.06,
   "ausschuettend": true,
   "sektor": "Dividenden",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vym",
   "art": "etf",
   "name": "Vanguard High Dividend Yield ETF",
   "kuerzel": "VYM",
   "kurs": 139.62,
   "kursOriginal": 162.69,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 83.3,
   "anzahlPositionen": 615,
   "ter": 0.04,
   "ausschuettend": true,
   "sektor": "Dividenden",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlk",
   "art": "etf",
   "name": "Technology Select Sector SPDR",
   "kuerzel": "XLK",
   "kurs": 161.23,
   "kursOriginal": 187.87,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 122,
   "anzahlPositionen": 76,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Technologie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "soxx",
   "art": "etf",
   "name": "iShares Semiconductor ETF",
   "kuerzel": "SOXX",
   "kurs": 456.57,
   "kursOriginal": 532,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 42.6,
   "anzahlPositionen": 34,
   "ter": 0.33,
   "ausschuettend": true,
   "sektor": "Halbleiter",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlv",
   "art": "etf",
   "name": "Health Care Select Sector SPDR",
   "kuerzel": "XLV",
   "kurs": 142.96,
   "kursOriginal": 166.58,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 43.3,
   "anzahlPositionen": 63,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Gesundheit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlf",
   "art": "etf",
   "name": "Financial Select Sector SPDR",
   "kuerzel": "XLF",
   "kurs": 48.9701,
   "kursOriginal": 57.06,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 55.3,
   "anzahlPositionen": 80,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Finanzen",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xle",
   "art": "etf",
   "name": "Energy Select Sector SPDR",
   "kuerzel": "XLE",
   "kurs": 56.0505,
   "kursOriginal": 65.31,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 42.5,
   "anzahlPositionen": 24,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Energie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vnq",
   "art": "etf",
   "name": "Vanguard Real Estate ETF",
   "kuerzel": "VNQ",
   "kurs": 81.4796,
   "kursOriginal": 94.94,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 37.5,
   "anzahlPositionen": 154,
   "ter": 0.13,
   "ausschuettend": true,
   "sektor": "Immobilien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "gld",
   "art": "etf",
   "name": "SPDR Gold Shares",
   "kuerzel": "GLD",
   "kurs": 346.16,
   "kursOriginal": 403.35,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 148.5,
   "anzahlPositionen": 2,
   "ter": 0.4,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "agg",
   "art": "etf",
   "name": "iShares Core US Aggregate Bond ETF",
   "kuerzel": "AGG",
   "kurs": 82.9729,
   "kursOriginal": 96.68,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 138.2,
   "anzahlPositionen": 13390,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "tlt",
   "art": "etf",
   "name": "iShares 20+ Year Treasury Bond ETF",
   "kuerzel": "TLT",
   "kurs": 70.1425,
   "kursOriginal": 81.73,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 46.9,
   "anzahlPositionen": 48,
   "ter": 0.15,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "vcit",
   "art": "etf",
   "name": "Vanguard Interm.-Term Corp. Bond ETF",
   "kuerzel": "VCIT",
   "kurs": 68.9238,
   "kursOriginal": 80.31,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 69.5,
   "anzahlPositionen": 2282,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "ibit",
   "art": "etf",
   "name": "iShares Bitcoin Trust",
   "kuerzel": "IBIT",
   "kurs": 38.0106,
   "kursOriginal": 44.29,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 61.6,
   "anzahlPositionen": 2,
   "ter": 0.25,
   "ausschuettend": true,
   "sektor": "Krypto",
   "anlageklasse": "Krypto",
   "land": null
  },
  {
   "id": "spy",
   "art": "etf",
   "name": "SPDR S&P 500 ETF Trust",
   "kuerzel": "SPY",
   "kurs": 654.31,
   "kursOriginal": 762.4,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 806.1,
   "anzahlPositionen": 505,
   "ter": 0.09,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ivv",
   "art": "etf",
   "name": "iShares Core S&P 500 ETF",
   "kuerzel": "IVV",
   "kurs": 657.48,
   "kursOriginal": 766.1,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 849.5,
   "anzahlPositionen": 508,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "vti",
   "art": "etf",
   "name": "Vanguard Total Stock Market ETF",
   "kuerzel": "VTI",
   "kurs": 322.31,
   "kursOriginal": 375.56,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 690.3,
   "anzahlPositionen": 3498,
   "ter": 0.03,
   "ausschuettend": true,
   "sektor": "USA breit",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iefa",
   "art": "etf",
   "name": "iShares Core MSCI EAFE ETF",
   "kuerzel": "IEFA",
   "kurs": 85.3244,
   "kursOriginal": 99.42,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 194.4,
   "anzahlPositionen": 2641,
   "ter": 0.07,
   "ausschuettend": true,
   "sektor": "Europa/Asien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "iemg",
   "art": "etf",
   "name": "iShares Core MSCI Emerging Markets ETF",
   "kuerzel": "IEMG",
   "kurs": 71.447,
   "kursOriginal": 83.25,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 164.6,
   "anzahlPositionen": 2896,
   "ter": 0.09,
   "ausschuettend": true,
   "sektor": "Schwellenlaender",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ewj",
   "art": "etf",
   "name": "iShares MSCI Japan ETF",
   "kuerzel": "EWJ",
   "kurs": 83.2475,
   "kursOriginal": 97,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 23.5,
   "anzahlPositionen": 173,
   "ter": 0.49,
   "ausschuettend": true,
   "sektor": "Japan",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "ezu",
   "art": "etf",
   "name": "iShares MSCI Eurozone ETF",
   "kuerzel": "EZU",
   "kurs": 59.758,
   "kursOriginal": 69.63,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 9.9,
   "anzahlPositionen": 226,
   "ter": 0.5,
   "ausschuettend": true,
   "sektor": "Eurozone",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "fxi",
   "art": "etf",
   "name": "iShares China Large-Cap ETF",
   "kuerzel": "FXI",
   "kurs": 29.6516,
   "kursOriginal": 34.55,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 4.3,
   "anzahlPositionen": 59,
   "ter": 0.74,
   "ausschuettend": true,
   "sektor": "China",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "inda",
   "art": "etf",
   "name": "iShares MSCI India ETF",
   "kuerzel": "INDA",
   "kurs": 41.7697,
   "kursOriginal": 48.67,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 6.7,
   "anzahlPositionen": 175,
   "ter": 0.61,
   "ausschuettend": true,
   "sektor": "Indien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xli",
   "art": "etf",
   "name": "Industrial Select Sector SPDR",
   "kuerzel": "XLI",
   "kurs": 147.43,
   "kursOriginal": 171.79,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 31.7,
   "anzahlPositionen": 86,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Industrie",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xly",
   "art": "etf",
   "name": "Consumer Discretionary Select Sector SPDR",
   "kuerzel": "XLY",
   "kurs": 96.5156,
   "kursOriginal": 112.46,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22,
   "anzahlPositionen": 50,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Konsum",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlp",
   "art": "etf",
   "name": "Consumer Staples Select Sector SPDR",
   "kuerzel": "XLP",
   "kurs": 71.2753,
   "kursOriginal": 83.05,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 14.4,
   "anzahlPositionen": 38,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Nahrung",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlu",
   "art": "etf",
   "name": "Utilities Select Sector SPDR",
   "kuerzel": "XLU",
   "kurs": 36.852,
   "kursOriginal": 42.94,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22.4,
   "anzahlPositionen": 34,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Versorger",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "xlc",
   "art": "etf",
   "name": "Communication Services Select Sector SPDR",
   "kuerzel": "XLC",
   "kurs": 95.1167,
   "kursOriginal": 110.83,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 22.7,
   "anzahlPositionen": 27,
   "ter": 0.08,
   "ausschuettend": true,
   "sektor": "Medien",
   "anlageklasse": "Aktien",
   "land": null
  },
  {
   "id": "slv",
   "art": "etf",
   "name": "iShares Silver Trust",
   "kuerzel": "SLV",
   "kurs": 52.1112,
   "kursOriginal": 60.72,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 32.7,
   "anzahlPositionen": 1,
   "ter": 0.5,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "dbc",
   "art": "etf",
   "name": "Invesco DB Commodity Index Tracking Fund",
   "kuerzel": "DBC",
   "kurs": 28.1926,
   "kursOriginal": 32.85,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 1.9,
   "anzahlPositionen": 38,
   "ter": 0.84,
   "ausschuettend": true,
   "sektor": "Rohstoffe",
   "anlageklasse": "Rohstoff",
   "land": null
  },
  {
   "id": "lqd",
   "art": "etf",
   "name": "iShares iBoxx Investment Grade Corporate Bond ETF",
   "kuerzel": "LQD",
   "kurs": 90.3793,
   "kursOriginal": 105.31,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 29.8,
   "anzahlPositionen": 3143,
   "ter": 0.14,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "hyg",
   "art": "etf",
   "name": "iShares iBoxx High Yield Corporate Bond ETF",
   "kuerzel": "HYG",
   "kurs": 67.7824,
   "kursOriginal": 78.98,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 15.4,
   "anzahlPositionen": 1333,
   "ter": 0.49,
   "ausschuettend": true,
   "sektor": "Anleihen",
   "anlageklasse": "Anleihen",
   "land": null
  },
  {
   "id": "etha",
   "art": "etf",
   "name": "iShares Ethereum Trust",
   "kuerzel": "ETHA",
   "kurs": 15.9458,
   "kursOriginal": 18.58,
   "waehrungOriginal": "USD",
   "fondsvolumenMrd": 8.8,
   "anzahlPositionen": 2,
   "ter": 0.25,
   "ausschuettend": true,
   "sektor": "Krypto",
   "anlageklasse": "Krypto",
   "land": null
  },
  {
   "id": "btc",
   "art": "krypto",
   "name": "Bitcoin",
   "kuerzel": "BTC",
   "kurs": 67035,
   "marktkapitalisierung": 1346207548574,
   "umlaufmenge": 20082225,
   "hoechstmenge": 21000000,
   "allzeithoch": 107662,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "eth",
   "art": "krypto",
   "name": "Ethereum",
   "kuerzel": "ETH",
   "kurs": 2122.86,
   "marktkapitalisierung": 259064364170,
   "umlaufmenge": 122035557,
   "hoechstmenge": null,
   "allzeithoch": 4229.76,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xrp",
   "art": "krypto",
   "name": "XRP",
   "kuerzel": "XRP",
   "kurs": 1.18,
   "marktkapitalisierung": 74337115717,
   "umlaufmenge": 62744504852,
   "hoechstmenge": 100000000000,
   "allzeithoch": 3.28,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "sol",
   "art": "krypto",
   "name": "Solana",
   "kuerzel": "SOL",
   "kurs": 86.96,
   "marktkapitalisierung": 50988019031,
   "umlaufmenge": 586335864,
   "hoechstmenge": null,
   "allzeithoch": 285.6,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "doge",
   "art": "krypto",
   "name": "Dogecoin",
   "kuerzel": "DOGE",
   "kurs": 0.073024,
   "marktkapitalisierung": 11381195222,
   "umlaufmenge": 155856026384,
   "hoechstmenge": null,
   "allzeithoch": 0.601466,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ada",
   "art": "krypto",
   "name": "Cardano",
   "kuerzel": "ADA",
   "kurs": 0.183356,
   "marktkapitalisierung": 6877774318,
   "umlaufmenge": 37510482444,
   "hoechstmenge": 45000000000,
   "allzeithoch": 2.61,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "link",
   "art": "krypto",
   "name": "Chainlink",
   "kuerzel": "LINK",
   "kurs": 10.14,
   "marktkapitalisierung": 7586988780,
   "umlaufmenge": 748099970,
   "hoechstmenge": 1000000000,
   "allzeithoch": 43.32,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ltc",
   "art": "krypto",
   "name": "Litecoin",
   "kuerzel": "LTC",
   "kurs": 45.02,
   "marktkapitalisierung": 3492849172,
   "umlaufmenge": 77591379,
   "hoechstmenge": 84000000,
   "allzeithoch": 337.56,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "avax",
   "art": "krypto",
   "name": "Avalanche",
   "kuerzel": "AVAX",
   "kurs": 6.65,
   "marktkapitalisierung": 2873318574,
   "umlaufmenge": 431771961,
   "hoechstmenge": 720000000,
   "allzeithoch": 128.43,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "dot",
   "art": "krypto",
   "name": "Polkadot",
   "kuerzel": "DOT",
   "kurs": 0.944258,
   "marktkapitalisierung": 1607205465,
   "umlaufmenge": 1702083270,
   "hoechstmenge": 2100000000,
   "allzeithoch": 47.6,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "bnb",
   "art": "krypto",
   "name": "BNB",
   "kuerzel": "BNB",
   "kurs": 616.49,
   "marktkapitalisierung": 82092595467,
   "umlaufmenge": 133161248,
   "hoechstmenge": 200000000,
   "allzeithoch": 1182.86,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "trx",
   "art": "krypto",
   "name": "Tron",
   "kuerzel": "TRX",
   "kurs": 0.292459,
   "marktkapitalisierung": 27766656117,
   "umlaufmenge": 94942001308,
   "hoechstmenge": null,
   "allzeithoch": 0.410308,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "ton",
   "art": "krypto",
   "name": "Toncoin",
   "kuerzel": "TON",
   "kurs": 1.18,
   "marktkapitalisierung": 3273813190,
   "umlaufmenge": 2785702823,
   "hoechstmenge": null,
   "allzeithoch": 7.7,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "aave",
   "art": "krypto",
   "name": "Aave",
   "kuerzel": "AAVE",
   "kurs": 106.5,
   "marktkapitalisierung": 1643103716,
   "umlaufmenge": 15427527,
   "hoechstmenge": 16000000,
   "allzeithoch": 541.28,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xlm",
   "art": "krypto",
   "name": "Stellar",
   "kuerzel": "XLM",
   "kurs": 0.15419,
   "marktkapitalisierung": 5366894965,
   "umlaufmenge": 34807090055,
   "hoechstmenge": null,
   "allzeithoch": 0.729104,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "bch",
   "art": "krypto",
   "name": "Bitcoin Cash",
   "kuerzel": "BCH",
   "kurs": 212.79,
   "marktkapitalisierung": 4274305912,
   "umlaufmenge": 20087166,
   "hoechstmenge": 21000000,
   "allzeithoch": 3187.12,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "xmr",
   "art": "krypto",
   "name": "Monero",
   "kuerzel": "XMR",
   "kurs": 436.99,
   "marktkapitalisierung": 8216687247,
   "umlaufmenge": 18802767,
   "hoechstmenge": null,
   "allzeithoch": 685.48,
   "sektor": "Krypto",
   "land": null
  },
  {
   "id": "uni",
   "art": "krypto",
   "name": "Uniswap",
   "kuerzel": "UNI",
   "kurs": 5.18,
   "marktkapitalisierung": 3226846063,
   "umlaufmenge": 623212424,
   "hoechstmenge": 1000000000,
   "allzeithoch": 37.37,
   "sektor": "Krypto",
   "land": null
  }
 ]
};
